import { PlannerProvider, Plan, Issue } from "../types";

/**
 * Markdown-based planner that renders plans as formatted markdown output.
 * Uses a PlannerProvider for generation and handles output formatting.
 */
export class MarkdownPlanner {
  private planner: PlannerProvider;

  constructor(planner: PlannerProvider) {
    this.planner = planner;
  }

  async generate(issue: Issue, context?: string): Promise<string> {
    const plan = await this.planner.generatePlan(issue, context);
    return this.render(plan);
  }

  private render(plan: Plan): string {
    const lines: string[] = [];

    lines.push(`# Plan for Issue #${plan.issueNumber}: ${plan.issueTitle}`);
    lines.push("");
    lines.push(`**Effort:** ${plan.effort}`);
    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push(plan.raw);
    lines.push("");
    lines.push("---");
    lines.push(`*Generated by gh-pilot v0.1.0*`);

    return lines.join("\n");
  }
}
